In [1]:
import numpy as np
a = np.array([1,2,3])
print(a)

[1 2 3]


In [2]:
type(a)

numpy.ndarray

In [3]:
a1 =np.array([(1,2,3),(4,5,6),(7,8,9)])
print(a1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
print(a.ndim)

1


In [5]:
print(a1.ndim)

2


In [7]:
print(a.itemsize)

4


In [8]:
a2 = np.array([1.2,2.3])
print(a2)

[1.2 2.3]


In [9]:
print(a2.itemsize)

8


In [12]:
print(a2.dtype)

float64


In [13]:
print(a.dtype)

int32


In [14]:
print(a.size)

3


In [15]:
print(a1.size)

9


In [16]:
print(a1.shape)

(3, 3)


In [17]:
print(a.shape)

(3,)


In [24]:
t = (1,)
print(t)

(1,)


In [25]:
type(t)

tuple

In [26]:
a3 = np.array([1,2,3,4,5,6,7,8,9])
print(a3)

[1 2 3 4 5 6 7 8 9]


In [29]:
a4 = a3.reshape(3,3)

In [30]:
print(a4)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [31]:
a4.max()

9

In [32]:
a4.min()

1

In [40]:
np.linspace(5,50,num=100,endpoint=False,retstep=True)

(array([ 5.  ,  5.45,  5.9 ,  6.35,  6.8 ,  7.25,  7.7 ,  8.15,  8.6 ,
         9.05,  9.5 ,  9.95, 10.4 , 10.85, 11.3 , 11.75, 12.2 , 12.65,
        13.1 , 13.55, 14.  , 14.45, 14.9 , 15.35, 15.8 , 16.25, 16.7 ,
        17.15, 17.6 , 18.05, 18.5 , 18.95, 19.4 , 19.85, 20.3 , 20.75,
        21.2 , 21.65, 22.1 , 22.55, 23.  , 23.45, 23.9 , 24.35, 24.8 ,
        25.25, 25.7 , 26.15, 26.6 , 27.05, 27.5 , 27.95, 28.4 , 28.85,
        29.3 , 29.75, 30.2 , 30.65, 31.1 , 31.55, 32.  , 32.45, 32.9 ,
        33.35, 33.8 , 34.25, 34.7 , 35.15, 35.6 , 36.05, 36.5 , 36.95,
        37.4 , 37.85, 38.3 , 38.75, 39.2 , 39.65, 40.1 , 40.55, 41.  ,
        41.45, 41.9 , 42.35, 42.8 , 43.25, 43.7 , 44.15, 44.6 , 45.05,
        45.5 , 45.95, 46.4 , 46.85, 47.3 , 47.75, 48.2 , 48.65, 49.1 ,
        49.55]),
 0.45)

In [41]:
np.sum(a4)

45

In [43]:
print(a4)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [42]:
np.sum(a4,axis=0)

array([12, 15, 18])

In [44]:
np.sum(a4,axis=1)

array([ 6, 15, 24])

In [45]:
np.sqrt(a4)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])